version: '3.8'

services:
  db:
    image: postgres:17.2
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test-api-db
    ports:
      - "5432:5432"

volumes:
  pg_data:
